rule register_contacts:
    input:
        in_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
        ref_im=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        transform_matrix=get_reg_matrix(),
    output:
        out_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            space="T1w",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/apply_registration.py"


rule contacts_qc:
    input:
        ct_img=get_registered_ct_image(),
        t1w_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        contact_fcsv_labelled=bids(
            root=config["output_dir"],
            datatype="slicer_fcsv",
            suffix="labelled_contactseg.fcsv",
            **inputs["post_ct"].wildcards,
        ),
        planned_fcsv=bids(
            root=config["bids_dir"],
            suffix="planned",
            extension=".fcsv",
            **inputs["post_ct"].wildcards,
        ),
    output:
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="contactseg",
            suffix="qc.html",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/contacts_qc.py"

rule nonlinear_t1_to_mni:
    input:
        t1_in_mni_img=bids(
            root=config["output_dir"],
            datatype="anat",
            session="pre",
            space="MNI",
            suffix="T1w.nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        mni_template="/local/scratch/contactseg/resources/atlases/tpl-MNI152NLin2009cSym_res-1_T1w.nii.gz"
    output:
        forward_warp=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="Warp.nii.gz",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
        inverse_warp=bids(
            root=config["output_dir"],
            desc="mni_to_t1",
            suffix="InverseWarp.nii.gz",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
        affine_syn=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="Affine.mat",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
    script:
        "../scripts/nonlinear_registration.py"


rule apply_full_transformation:
    input:
        coords=bids(
                root=config["output_dir"],
                suffix="labelled_contactseg.fcsv",
                datatype="slicer_fcsv",
                **inputs["post_ct"].wildcards,
        ),
        forward_warp=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="Warp.nii.gz",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
        affine_syn=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="Affine.mat",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
        affine=bids(
            root=config["output_dir"],
            datatype="registration",
            desc="from_T1w-to-MNI",
            suffix="slicer.mat",
            **inputs["pre_t1w"].wildcards,
        )
    output: 
        output_coords=bids(
            root=config["output_dir"],
            suffix="mni_transformed_contactseg.fcsv",
            datatype="slicer_fcsv",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/apply_full_transformation.py"


rule transform_atlas_to_t1:
    input:
        atlas_image="/local/scratch/contactseg/resources/atlases/tpl-MNI152NLin2009cSym_res-1_atlas-CerebrA_dseg.nii",  
        t1_image=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        inverse_warp=bids(
            root=config["output_dir"],
            desc="mni_to_t1",
            suffix="InverseWarp.nii.gz",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
        affine=bids(
            root=config["output_dir"],
            datatype="registration",
            desc="from_T1w-to-MNI",
            suffix="slicer.mat",
            **inputs["pre_t1w"].wildcards,
        ),
        affine_syn=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="Affine.mat",
            datatype="nonlinear_registration",
            **inputs["pre_t1w"].wildcards,
        ),
    output:
        atlas_in_t1=bids(
            root=config["output_dir"],
            suffix="atlas_in_t1_space.nii.gz",
            datatype="anat",
            session="post",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/transform_atlas_to_t1.py"