rule register_contacts:
    input:
        in_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
        ref_im=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        transform_matrix=get_reg_matrix(),
    output:
        out_im=bids(
            root=config["output_dir"],
            suffix="dseg.nii.gz",
            space="T1w",
            desc="contacts_nnUNet",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/apply_registration.py"


rule contacts_qc:
    input:
        ct_img=get_registered_ct_image(),
        t1w_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        contact_fcsv_labelled=bids(
            root=config["output_dir"],
            datatype="slicer_fcsv",
            suffix="labelled_contactseg.fcsv",
            **inputs["post_ct"].wildcards,
        ),
        planned_fcsv=bids(
            root=config["bids_dir"],
            suffix="planned",
            extension=".fcsv",
            **inputs["post_ct"].wildcards,
        ),
    output:
        html=bids(
            root=config["output_dir"],
            datatype="qc",
            desc="contactseg",
            suffix="qc.html",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/contacts_qc.py"

rule nonlinear_t1_to_mni:
    input:
        t1_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        mni_template="resources/MNI152_template.nii.gz"
    output:
        forward_warp=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="1Warp.nii.gz",
            datatype="anat",
            session="pre",
            **inputs["pre_t1w"].wildcards,
        ),
        inverse_warp=bids(
            root=config["output_dir"],
            desc="mni_to_t1",
            suffix="1InverseWarp.nii.gz",
            datatype="anat",
            session="pre",
            **inputs["pre_t1w"].wildcards,
        ),
        affine=bids(
            root=config["output_dir"],
            desc="t1_to_mni",
            suffix="0GenericAffine.mat",
            datatype="anat",
            session="pre",
            **inputs["pre_t1w"].wildcards,
        ),
    script:
        "../scripts/nonlinear_registration.py"

rule warp_mni_to_t1:
    input:
        atlas_img="resources/atlas_subcortical.nii.gz",
        t1_img=bids(
            root=config["output_dir"],
            suffix="T1w",
            desc="n4",
            datatype="anat",
            session="pre",
            extension=".nii.gz",
            **inputs["pre_t1w"].wildcards,
        ),
        inverse_warp=rules.nonlinear_t1_to_mni.output.inverse_warp,
        affine=rules.nonlinear_t1_to_mni.output.affine,
    output:
        atlas_in_t1=bids(
            root=config["output_dir"],
            desc="atlas",
            suffix="atlas_subcortical_in_t1_space.nii.gz",
            datatype="anat",
            session="pre",
            **inputs["pre_t1w"].wildcards,
        ),
    script:
        "../scripts/warp_mni_to_t1.py"

rule label_contacts_by_atlas:
    input:
        coords=rules.transform_coords.output.transformed_coords,  
        atlas_in_t1=rules.warp_mni_to_t1.output.atlas_in_t1,
        atlas_labels="resources/atlas_subcortical.xml",
    output:
        labelled_coords=bids(
            root=config["output_dir"],
            suffix="atlas_labelled_contactseg.fcsv",
            datatype="slicer_fcsv",
            **inputs["post_ct"].wildcards,
        ),
    script:
        "../scripts/label_contacts_by_atlas.py"
