"""Export an atlas segmentation as a 3D Slicer .seg.nrrd segmentation.

Slicer reads a plain NIfTI label map as a scalar volume; writing the
segmentation metadata (one named, coloured segment per label) instead means the
atlas loads straight into the Segmentations module, next to the contacts.

Adapted from the ieegProc nii-to-nrrd conversion.
"""

import colorsys

import nibabel as nib
import numpy as np
import nrrd
import pandas as pd

GOLDEN_RATIO = 0.618033988749895


def label_color(key, table_row=None):
    """Return an RGB tuple in 0-1 for ``key``."""
    if table_row is not None and {"r", "g", "b"} <= set(table_row.index):
        return (
            float(table_row["r"]) / 255,
            float(table_row["g"]) / 255,
            float(table_row["b"]) / 255,
        )

    return colorsys.hsv_to_rgb((key * GOLDEN_RATIO) % 1.0, 0.6, 0.9)


def read_lut(lut_file):
    """Read a dseg.tsv into ``{index: (name, row)}``, or an empty dict."""
    if not lut_file:
        return {}

    table = pd.read_csv(lut_file, sep="\t")
    table.columns = table.columns.str.lower()

    lut = {}
    for _, row in table.iterrows():
        name = str(row["name"])
        if "hemi" in table.columns and str(row["hemi"]) in ("L", "R"):
            name = f"{row['hemi']}_{name}"
        lut[int(row["label"])] = (name, row)

    return lut


def write_nrrd(img, output_nrrd, lut, orientation="ras"):
    """Write ``img`` as a Slicer segmentation, one segment per label."""
    data = np.rint(img.get_fdata()).astype(np.int16)
    shape = data.shape

    fields = {
        "dimension": 3,
        "encoding": "gzip",
        "kinds": ["domain", "domain", "domain"],
        "type": "int",
        "sizes": np.array(shape, dtype=int),
    }

    if orientation == "ras":
        fields["space"] = "right-anterior-superior"
        fields["space directions"] = img.affine[:3, :3].T
        fields["space origin"] = img.affine[:3, 3]
    else:
        fields["space"] = "left-posterior-superior"
        flip = np.diag([-1.0, -1.0, 1.0])
        fields["space directions"] = (flip @ img.affine[:3, :3]).T
        fields["space origin"] = img.affine[:3, 3] * np.array([-1, -1, 1])

    for count, index in enumerate(np.unique(data)[np.unique(data) > 0]):
        name, row = lut.get(int(index), (f"Label_{int(index)}", None))
        color = label_color(int(index), row)
        segment = f"Segment{count}"
        fields[f"{segment}_Color"] = " ".join(f"{c:1.3f}" for c in color)
        fields[f"{segment}_ColorAutoGenerated"] = "1"
        fields[f"{segment}_Extent"] = (
            f"0 {shape[0] - 1} 0 {shape[1] - 1} 0 {shape[2] - 1}"
        )
        fields[f"{segment}_ID"] = f"Segment_{int(index)}"
        fields[f"{segment}_LabelValue"] = f"{int(index)}"
        fields[f"{segment}_Layer"] = "0"
        fields[f"{segment}_Name"] = name
        fields[f"{segment}_NameAutoGenerated"] = "0"

    fields["Segmentation_ContainedRepresentationNames"] = "Binary labelmap|"
    fields["Segmentation_MasterRepresentation"] = "Binary labelmap"
    fields["Segmentation_ReferenceImageExtentOffset"] = "0 0 0"

    nrrd.write(output_nrrd, data, fields)


def atlas_dseg_to_nrrd(atlas_dseg, lut_file, output_nrrd, orientation):
    """
    Function that exports an atlas segmentation for 3D Slicer.

    Parameters
    ----------
    atlas_dseg : str
        Path to the atlas segmentation.
    lut_file : str or None
        Path to a dseg.tsv naming and colouring the labels.
    output_nrrd : str
        Path to save the .seg.nrrd file.
    orientation : str
        ``ras`` or ``lps``.

    Returns
    -------
    None
    """

    write_nrrd(
        nib.load(atlas_dseg),
        output_nrrd,
        read_lut(lut_file),
        orientation=orientation,
    )


def first_or_none(value):
    """Return a single path from an input that may be an empty list."""
    if isinstance(value, (list, tuple)):
        return value[0] if value else None

    return value or None


if __name__ == "__main__":
    atlas_dseg_to_nrrd(
        atlas_dseg=snakemake.input.atlas_dseg,
        lut_file=first_or_none(snakemake.input.lut),
        output_nrrd=snakemake.output.seg_nrrd,
        orientation=snakemake.params.orientation,
    )
